### ISSUE TITLE
[On-Chain] Ensure all message responses contain results

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#663]
## Objective

Ensure message responses contain the respective created/updated resources.

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/600733/b466bd2f-b008-419a-b60b-a1ece32ebf7d)

## Goals

- Improve developer experience.

## Deliverables

- [x] A PR for each module which updates all message reponse types to include the created/updated object.
- [ ] A PR which adds a CLI tool which detects protobuf msg/query reponse types that don't contain any fields (proto and go source).
  - (#970)
- [ ] A PR which runs the CLI tool in CI to mitigate regressions on the `main` branch.

## Non-goals / Non-deliverables

- Refactoring protobuf types or message handlers outside the scope of this issue.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @red-0ne

**Comment by bryanchriswhite** [comment]
## Complications

As soon as I try to import `poktroll.application.Application` for use in `poktroll.application.MsgDelegateToGateway`, the generated pulsar go source changes in an unexpected way:

![image](https://github.com/pokt-network/poktroll/assets/600733/540eaeb2-dde6-42b7-a051-70f7a722f85f)

When subsequently produces the following error when running application module integration tests:

```
recovered: message poktroll.MsgDelegateToGateway does not contain field poktroll.application.MsgDelegateToGateway.app_address
stack:
goroutine 104 [running]:
runtime/debug.Stack()
... 
github.com/cosmos/cosmos-sdk/testutil/cli.ExecTestCLICmd({{0x0, 0x0, 0x0}, {0x7f7ffc24dc08, 0xc000d11380}, 0x0, {0xc0003c55d0, 0xc}, {0x53503e8, 0xc0012b07e0}, ...}, ...)
	/home/bwhite/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.4/testutil/cli/cmd.go:26 +0x2bb
github.com/pokt-network/poktroll/x/application/module_test.TestCLI_DelegateToGateway.func1(0xc009322340)
	/home/bwhite/Projects/pokt/poktroll/x/application/module/tx_delegate_to_gateway_test.go:98 +0x3fb
testing.tRunner(0xc009322340, 0xc009542fc0)
	/home/bwhite/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1689 +0x1da
created by testing.(*T).Run in goroutine 16
	/home/bwhite/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1742 +0x7d3
: panic
```

For comparison, here's what the pulsar go source should look like:

![image](https://github.com/pokt-network/poktroll/assets/600733/347c60b5-508b-46b8-8ae7-a34bfeb03474)

**Comment by bryanchriswhite** [comment]
NB: Updating the buf.gen.pulsar.yaml like so had no effect:

```diff
-    opt: paths=source_relative,Mpoktroll/shared/service.proto=github.com/pokt-network/poktroll/api/poktroll/shared,Mpoktroll/shared/supplier.proto=github.com/pokt-network/poktroll/api/poktroll/shared,Mpoktroll/application/application.proto=github.com/pokt-network/poktroll/api/poktroll/application,Mpoktroll/supplier/supplier.proto=github.com/pokt-network/poktroll/api/poktroll/supplier,Mpoktroll/session/session.proto=github.com/pokt-network/poktroll/api/poktroll/session
+    opt: paths=source_relative,Mpoktroll/shared/service.proto=github.com/pokt-network/poktroll/api/poktroll/shared,Mpoktroll/shared/supplier.proto=github.com/pokt-network/poktroll/api/poktroll/shared,Mpoktroll/application/application.proto=github.com/pokt-network/poktroll/api/poktroll/application,Mpoktroll/supplier/supplier.proto=github.com/pokt-network/poktroll/api/poktroll/supplier,Mpoktroll/session/session.proto=github.com/pokt-network/poktroll/api/poktroll/session,Mpoktroll/application/tx.proto=github.com/pokt-network/poktroll/api/poktroll/application

```

**Comment by bryanchriswhite** [comment]
The issue outlined above should be resolved by https://github.com/pokt-network/poktroll/issues/405#issuecomment-2302174459
